# Generated by Django 5.0.7 on 2024-09-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelasor',
            name='name',
        ),
    ]
