# Generated by Django 5.0.7 on 2024-09-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_kelasor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parvande',
            name='kelasor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parvandes', to='app1.kelasor'),
        ),
    ]
