# Generated by Django 5.0.7 on 2024-09-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_parvande_kelasor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parvande',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
