# Generated by Django 5.0.7 on 2024-09-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_parvande_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parvande',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
