# Generated by Django 5.0.7 on 2024-09-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_parvande_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parvande',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
